version: '3.8'
services:
  activity-microservice:
    image: activity-microservice
    build:
      context: .
      dockerfile: ./apps/activity-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/activity-service/main.microservice.js
    command: npm run start-microservice-activity:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  affiliate-microservice:
    image: affiliate-microservice
    build:
      context: .
      dockerfile: ./apps/affiliate-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/affiliate-service/main.microservice.js
    command: npm run start-microservice-affiliate:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  brand-microservice:
    image: brand-microservice
    build:
      context: .
      dockerfile: ./apps/brand-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/brand-service/main.microservice.js
    command: npm run start-microservice-brand:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  category-microservice:
    image: category-microservice
    build:
      context: .
      dockerfile: ./apps/category-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/category-service/main.microservice.js
    command: npm run start-microservice-category:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  # communication-microservice:
  #   image: communication-microservice
  #   build:
  #     context: .
  #     dockerfile: ./apps/communication-service/dockerfile
  #     target: dev
  #   #command: node /usr/src/app/dist/apps/communication-service/main.microservice.js
  #   command: npm run start-microservice-communication:debug
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: on-failure
  crm-microservice:
    image: crm-microservice
    build:
      context: .
      dockerfile: ./apps/crm-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/crm-service/main.microservice.js
    command: npm run start-microservice-crm:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  file-microservice:
    image: file-microservice
    build:
      context: .
      dockerfile: ./apps/file-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/file-service/main.microservice.js
    command: npm run start-microservice-file:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  group-microservice:
    image: group-microservice
    build:
      context: .
      dockerfile: ./apps/group-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/group-service/main.microservice.js
    command: npm run start-microservice-group:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  ip-address-microservice:
    image: ip-address-microservice
    build:
      context: .
      dockerfile: ./apps/ip-address-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/ip-address-service/main.microservice.js
    command: npm run start-microservice-ip-address:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  lead-microservice:
    image: lead-microservice
    build:
      context: .
      dockerfile: ./apps/lead-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/lead-service/main.microservice.js
    command: npm run start-microservice-lead:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  message-microservice:
    image: message-microservice
    build:
      context: .
      dockerfile: ./apps/message-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/message-service/main.microservice.js
    command: npm run start-microservice-message:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  permission-microservice:
    image: permission-microservice
    build:
      context: .
      dockerfile: ./apps/permission-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/permission-service/main.microservice.js
    command: npm run start-microservice-permission:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  person-microservice:
    image: person-microservice
    build:
      context: .
      dockerfile: ./apps/person-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/person-service/main.microservice.js
    command: npm run start-microservice-person:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  psp-microservice:
    image: psp-microservice
    build:
      context: .
      dockerfile: ./apps/psp-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/psp-service/main.microservice.js
    command: npm run start-microservice-psp:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  role-microservice:
    image: role-microservice
    build:
      context: .
      dockerfile: ./apps/role-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/role-service/main.microservice.js
    command: npm run start-microservice-role:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  stats-microservice:
    image: stats-microservice
    build:
      context: .
      dockerfile: ./apps/stats-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/stats-service/main.microservice.js
    command: npm run start-microservice-stats:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  status-microservice:
    image: status-microservice
    build:
      context: .
      dockerfile: ./apps/status-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/status-service/main.microservice.js
    command: npm run start-microservice-status:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  traffic-microservice:
    image: traffic-microservice
    build:
      context: .
      dockerfile: ./apps/traffic-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/traffic-service/main.microservice.js
    command: npm run start-microservice-traffic:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  transfer-microservice:
    image: transfer-microservice
    build:
      context: .
      dockerfile: ./apps/transfer-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/transfer-service/main.microservice.js
    command: npm run start-microservice-transfer:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
  user-microservice:
    image: user-microservice
    build:
      context: .
      dockerfile: ./apps/user-service/dockerfile
      target: dev
    #command: node /usr/src/app/dist/apps/user-service/main.microservice.js
    command: npm run start-microservice-user:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure