# version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
    volumes:
      - ./../../localstorage/rmq/data/:/var/lib/rabbitmq/
      - ./../../localstorage/rmq/log/:/var/log/rabbitmq/
    networks:
      - b2crypto_net
  mongodb:
    image: mongo:8.0.4-noble
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpwd
      MONGO_INITDB_DATABASE: b2crypto
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    volumes:
      - ./../../localstorage/mongo/data/:/data/db
    networks:
      - b2crypto_net
  redis:
    image: redis:6.2-alpine
    container_name: rediscache
    restart: always
    ports:
      - '6379:6379'
    environment:
      REDIS_DAEMON_USER: b2crypto
      REDIS_PASSWORD: b2crypto
      REDIS_MASTER_PASSWORD: b2crypto
    volumes:
      - ./../../localstorage/redis/data:/data
    networks:
      - b2crypto_net
  jaeger:
    image: jaegertracing/all-in-one:1.63.0
    container_name: jaeger
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
    environment:
      - LOG_LEVEL=debug
    networks:
      - b2crypto_net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    networks:
      - b2crypto_net
    volumes:
      - mailpit_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - MP_MAX_MESSAGES=5000
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

networks:
  b2crypto_net:
    driver: bridge

volumes:
  mailpit_data:
    driver: local
    name: mailpit_data
