name: CD Pipeline for B2crypto Monolith

on:
  pull_request:
    types:
      - closed
    branches: [stage, test, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_shared_iac:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if there are changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'iac_shared/**'

      - if: steps.changes.outputs.src == 'true'
        name: Get Commit SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - if: steps.changes.outputs.src == 'true'
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - if: steps.changes.outputs.src == 'true'
        name: Setup pnpm
        run: corepack enable pnpm

      - if: steps.changes.outputs.src == 'true'
        name: Install dependencies
        run: pnpm install

      - if: steps.changes.outputs.src == 'true'
        name: Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/testing' || 'b2fintech/staging' }}
          work-dir: ./iac_shared
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr: true
          diff: true
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}

  deploy_monolith_iac:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    needs: deploy_shared_iac
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/testing' || 'b2fintech/staging' }}
          work-dir: ./iac_monolith
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr: true
          diff: true
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}
