name: CD Pipeline for B2crypto Monolith

on:
  pull_request:
    types:
      - closed
    branches: [stage, test, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Pulumi Up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/testing' || 'b2fintech/staging' }}
          work-dir: ./iac
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr: true
          diff: true
          color: always
          parallel: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}
