name: CI Pipeline for B2crypto Monolith Cloud Services

on:
  pull_request:
    branches: [stage, test, main]
    paths:
      - 'iac/cloud-services/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview_deploy_cloud_services:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    needs: preview_deploy_app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/testing' || 'b2fintech/staging' }}
          work-dir: ./iac/cloud-services
          # comment-on-pr: true
          # diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ steps.commit.outputs.short }}
