name: CI/CD Pipeline for B2crypto Monolith

on:
  pull_request:
    branches: [stage, test, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      # - name: Lint code
      #   run: npm run lint

      # - name: Run unit tests
      #   run: npm test

      # - name: Run integration tests
      #   run: npm run test:e2e

      - name: Build
        run: npm run build

  preview_deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'production' || github.event.pull_request.base.ref == 'test' && 'testing' || 'staging' }}
          work-dir: ./iac
          # comment-on-pr: true
          # diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    needs: [build, preview_deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit SHA
        uses: prompt/actions-commit-hash@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'production' || github.event.pull_request.base.ref == 'test' && 'testing' || 'staging' }}
          work-dir: ./iac
          # comment-on-pr: true
          # diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ steps.commit.outputs.short }}
