name: CI Pipeline for B2crypto Monolith

on:
  pull_request:
    branches: [stage, test, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: npm run format

      # - name: Lint code
      #   run: npm run lint

      # - name: Run unit tests
      #   run: npm test

      # - name: Run integration tests
      #   run: npm run test:e2e

      - name: Build
        run: npm run build

  preview_deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Commit SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Pulumi Preview
        uses: pulumi/actions@v6
        with:
          command: preview
          #stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/testing' || 'b2fintech/staging' }}
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/b2crypto-iac/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/b2crypto-iac/testing' || 'b2fintech/b2crypto-iac/staging' }}
          work-dir: ./iac
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr: true
          diff: true
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}
