name: CI Pipeline for B2crypto Monolith

on:
  pull_request:
    branches: [stage, test, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      # - name: Lint code
      #   run: npm run lint

      # - name: Run unit tests
      #   run: npm test

      # - name: Run integration tests
      #   run: npm run test:e2e

      - name: Build
        run: npm run build

  # preview_push_image:
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci

  #     - uses: pulumi/actions@v5
  #       with:
  #         command: preview
  #         stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/testing' || 'b2fintech/staging' }}
  #         work-dir: ./iac/app
  #         # comment-on-pr: true
  #         # diff: true
  #       env:
  #         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  #         COMMIT_SHA: ${{ steps.commit.outputs.short }}

  preview_deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    # needs: preview_push_image
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Pulumi Preview
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: ${{ github.event.pull_request.base.ref == 'main' && 'b2fintech/production' || github.event.pull_request.base.ref == 'test' && 'b2fintech/testing' || 'b2fintech/staging' }}
          work-dir: ./iac/cloud-services
          # comment-on-pr: true
          # diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          COMMIT_SHA: ${{ steps.commit.outputs.short }}
